network:
   ethernets:
      ens160:
         dhcp4: false
         addresses: [10.0.5.52/24]
         gateway4: 10.0.5.1
         nameservers:
            addresses: [10.0.5.1, 10.0.5.2, 10.0.5.3]
  version: 2
